[package]
name = "dao-voting"
version = "1.0"
edition = "2024"

[dependencies]
anchor-lang = "0.18.0"
anchor-spl = "0.18.0"
anchor-zk = { version = "0.1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
